#!/usr/bin/env node

let fs = require('fs')
let util = require('util')
let sh = require('..')

let log = (s) => { console.log(util.inspect(s, {depth: null})) }
let hr = () => console.log('-'.repeat(80))

let s = sh(fs.readFileSync(process.argv[2]).toString())
let pdata = s.parse()
log(pdata)

hr()
log(s.resolve(process.argv[3], pdata))

hr()
log(s.business(pdata, process.argv[3]))
