#!/usr/bin/env node

let fs = require('fs')
let util = require('util')
let sh = require('..')

let log = (s) => { console.log(util.inspect(s, {depth: null})) }
let hr = () => console.log('-'.repeat(80))

let s = sh(fs.readFileSync(process.argv[2]).toString())
log(s.parsed_input)

hr()
log(s.resolve(process.argv[3], s.parsed_input))

hr()
log(s.business(process.argv[3]))
